baseURL: https://grip.energy/
languageCode: en-us
title: Grip
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Grip Website
    description: "ExampleSite description"
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]

    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: false
    ShowShareButtons: false
    disableSpecial1stPost: true
    comments: false
    hidemeta: false
    showtoc:
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "GRIP"
    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: "GRIP"
        subtitle: "GRIP is a project led by the Department of Energy’s SLAC National Accelerator Laboratory that combines artificial intelligence with massive amounts of data and industry experience from a dozen U.S. partners to identify places where the electric grid is vulnerable to disruption, reinforce those spots in advance and recover faster when failures do occur."
        # imageUrl: "https://raw.githubusercontent.com/PresencePG/grip-client/a8e8ce832ae946ce698a1cb700e2d8d481a60f72/src/css/zeplin/DataManagement/img/sidebar.svg?token=AHAIV2ALO2EKQJNWKC52MFDAMIQ3C"
        imageWidth: 200
        imageHeight: 130
        imageTitle: my image

    # home-info mode
    homeInfoParams:
        Title: "GRIP"

        Content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

        Why do we use it?
        It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."

    socialIcons:
        - name: github
          url: "https://github.com/"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: Getting Started Guide
          name: Getting Started Guide
          url: /getting-started-guide/
          weight: 10
        - identifier: Use Cases
          name: Use Cases
          url: /use-cases/
          weight: 20
        - identifier: Publications
          name: Publications
          url: /publications/
          weight: 30
        - identifier: Team
          name: Team
          url: /team/
          weight: 40
        - identifier: Contact
          name: Contact
          url: /contact/
          weight: 50
